export { default as Logo } from './images/logo.png'
export { default as All } from './images/all.jpeg'
export { default as SocialMedia } from './images/social_media.png'
export { default as NaturalProcessing } from './images/natural_processing.png'
export { default as Profile } from './images/profile.png'
